In [27]:
%reload_ext autoreload
%autoreload 2

%matplotlib inline

import os
import sys
from pathlib import Path

import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
import seaborn as sns

if Path.cwd().name in {"notebooks", "research"}:
    os.chdir("..")

project_root = str(Path.cwd())
if project_root not in sys.path:
    sys.path.insert(0, project_root)

print(f"CWD: {Path.cwd()}")

CWD: c:\Users\reymo\quant-portfolio

In [28]:
from src.data.data_manager import DataManager
from src.analytics.tournaments import PortfolioTournament

start_date = "2019-01-01"
end_date = "2023-12-31"

dm = DataManager(base_dir="data/raw")

tickers = dm.list_existing_tickers()

returns = dm.load_returns(tickers=tickers, start_date=start_date, end_date=end_date)

returns.describe().T.head()

,count,mean,std,min,25%,50%,75%,max
AAPL,1033.0,0.001154,0.020858,-0.128647,-0.008785,0.000444,0.012396,0.119808
ABBV,1033.0,0.000826,0.015556,-0.130022,-0.006805,0.000674,0.008378,0.087174
ADBE,1033.0,0.000862,0.024492,-0.167932,-0.010567,0.000840,0.014097,0.177193
AIR.PA,1033.0,0.000472,0.028274,-0.221685,-0.011183,0.000758,0.011823,0.204633
AMZN,1033.0,0.000729,0.023417,-0.140494,-0.011653,0.000193,0.012793,0.135359

In [29]:
market_caps = dm.get_latest_market_cap(tickers)
market_caps.head()

AAPL      2.803317e+12
ABBV      2.532679e+11
ADBE      2.497367e+11
AIR.PA    1.060668e+11
AMZN      1.624271e+12
dtype: float64

In [30]:
PT = PortfolioTournament(returns, market_caps)
results = PT.run_all(market_caps)
weights_df = pd.concat(results, axis=1)
metrics_all = PT.calculate_metrics(weights_df, PT.sigma_ann)

metrics_all

                      Vol       HHI        DR
Market_cap       0.251193  0.054456  1.425137
MVO_tangency     0.248439  0.244528  1.501872
Black_Litterman  0.301046  0.255087  1.218060
HRP              0.182111  0.027155  1.654582