In [7]:
%reload_ext autoreload
%autoreload 2

%matplotlib inline

import os
import sys
from pathlib import Path

import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
import seaborn as sns

if Path.cwd().name in {"notebooks", "research"}:
    os.chdir("..")

project_root = str(Path.cwd())
if project_root not in sys.path:
    sys.path.insert(0, project_root)

print(f"CWD: {Path.cwd()}")

CWD: c:\Users\reymo\quant-portfolio

In [8]:
from src.data.data_manager import DataManager
from src.analytics.tournaments import PortfolioTournament

start_date = "2020-01-01"
end_date = "2025-12-31"

dm = DataManager()

tickers = dm.list_existing_tickers()

returns = dm.load_returns(tickers=tickers, start_date=start_date, end_date=end_date)

returns.describe().T.head()

,count,mean,std,min,25%,50%,75%,max
AAPL,1549.0,0.001051,0.019765,-0.128647,-0.007770,0.000581,0.010738,0.153288
ABBV,1549.0,0.000890,0.015508,-0.130023,-0.006358,0.000609,0.008688,0.087174
ADBE,1549.0,0.000310,0.023381,-0.167932,-0.009652,0.000140,0.012298,0.177193
AIR.PA,1549.0,0.000612,0.024875,-0.221685,-0.009700,0.000704,0.010853,0.204633
AMZN,1549.0,0.000824,0.022183,-0.140494,-0.010856,0.000251,0.012404,0.135359

In [9]:
market_caps = dm.get_latest_market_cap(tickers)
market_caps.head()

AAPL      4.009957e+12
ABBV      4.027981e+11
ADBE      1.475607e+11
AIR.PA    1.570392e+11
AMZN      2.496191e+12
dtype: float64

In [10]:
PT = PortfolioTournament(returns, market_caps)
results = PT.run_all(market_caps)
weights_df = pd.concat(results, axis=1)
metrics_all = PT.calculate_metrics(weights_df, PT.sigma_ann)

metrics_all

                      Vol       HHI        DR
Market_cap       0.255942  0.066798  1.435064
MVO_tangency     0.263201  0.251933  1.469207
Black_Litterman  0.304237  0.297113  1.226218
HRP              0.162505  0.026308  1.793869